### ISSUE TITLE
Append mode feedback in PyTestLog2DB

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/python-pytestlog2db#10]
I used `--append` but forgot to provide an UUID.

Result is this error message:
`WARN: '--append' argument should be used in combination with '--UUID <UUID>` argument.`

This is fine, but even so the application continues with writing results to database.

Here I have doubts. Because I want to add new results (and this means: maybe other results) to already existing ones. But because the append mode is not activated I get my previous results overwritten?

In case of errors in command line the application should stop with an error message.

In case of the application runs in append mode it would be helpful to have the final feedback:

`All test results are written to database successfully.`

modified in this way:

`All test results are written to database successfully (append mode).`

**Comment by test-fullautomation** [comment]
Hi Ngoan,
--append, but no UUID must result in an error and abort.
Thank you,
 Thomas

**Comment by test-fullautomation** [comment]
merged and solved with#20
