### ISSUE TITLE
Console output of PyTestLog2DB

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/python-pytestlog2db#11]
In case of a test case matches a pattern in the mapping table it would be helpful to have the name of the identified component displayed in console also.

Example:

Not:

`Created test case result for test 'test_Integer[Input parameter of type 'int'.]' successfully: 60590`

But:

`Created test case result for test 'test_Integer[Input parameter of type 'int'.]' successfully: 60590 (component: <component name>)`

**Comment by HolQue** [comment]
Addendum: Also other available parameters like `version_sw` and `variant` should be printed to log.

I have not checked but maybe this is also an issue for RobotLog2DB.

**Comment by test-fullautomation** [comment]
merged and solved with#20
