### ISSUE TITLE
Missing command line parameter

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/python-pytestlog2db#14]
RobotLog2DB provides the possibility to define missing values in command line with

--variant VARIANT and --versions VERSIONS

Why not also PyTestLog2DB?

Having the need always to edit the configuration file is unfavorable.

Also for testing purposes it would be better to have both applications implemented in the same way.

**Comment by test-fullautomation** [comment]
Hi Ngoan,

both tools need to have same command line interface.
Please also take care of the documentation.

Thank you,
 Thomas

**Comment by test-fullautomation** [comment]
merged and solved with #20
