### ISSUE TITLE
Duplicate component names in mapping table

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/python-pytestlog2db#15]
By mistake I implemented the mapping table of PyTestLog2DB in this way:

```
"PyExCollect" : "Comparison",
"PyExCollect" : "File",
"PyExCollect" : "Folder",
"PyExCollect" : "String",
"PyExCollect" : "Utils",
```

Outcome: Only the last rule ("Utils") maps the result to component "PyExCollect". The remaining ones are mapped to component "unknown".

I changed the mapping table to this:

`"PyExCollect" : ["Comparison", "File", "Folder", "String", "Utils"]`

Outcome: All test results mapped properly to component "PyExCollect".

But if the first format is not supported, then I expect an error message telling me about duplicate component names.
The app must not accept duplicate component names and has to stop the computation.

**Comment by HolQue** [comment]
Might it be the JSON parser who is not able to handle duplicate key names? Because of the mapping to a dictionary, where also key names must be unique?

How about exchanging the order:

```
"Comparison" : "PyExCollect",
"File"       : "PyExCollect",
"Folder"     : "PyExCollect",
"String"     : "PyExCollect",
"Utils"      : "PyExCollect"
```

Because the filter strings will be unique. This format would be a little bit more easy, because a list as sub level would not be required any more.

**Comment by test-fullautomation** [comment]
Hi Holger,

unfortunately I disagree to your propsal.

The component must be the key. The substring to be searched the value.
The array definition is meaningful and understandable in case of multiple substrings match to the same component.

You can also write like e.g.
```
"PyExCollect" : [ "Comparison", 
                  "File", 
                  "Folder", 
                  "String",
                  "Utils"
                 ]
```

@ngoan1608 : This must be supported and documented for all \*log2db\* tools.

Thank you,
 Thomas

**Comment by ngoan1608** [comment]
Hi,

The \*log2db\* tools have already implemented to support multiple substrings match to the same component as Thomas mentioned:
```
"PyExCollect" : [ "Comparison", 
                  "File", 
                  "Folder", 
                  "String",
                  "Utils"
                 ]
```
There is also example of configuration json file and explanation about component mapping in document file.

This ticket can be closed.

Thank you,
Ngoan
