### ISSUE TITLE
Change of default component name

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/python-pytestlog2db#16]
Test results without an entry in mapping table are automatically mapped to a component named "unknown".

I am not sure - but maybe it is a useful feature to have the possibility to influence this default name.

The use case would be: User has a bunch of test results. Some of them have to be mapped to certain components. All remaining test results, for which an individual rule in the mapping table would be too much or is really not required, shall be accumulated to a component with a user defined name.

In mapping table this could be realized with an entry e.g. like this:

`"BaseTests" : "[]"`

With "BaseTests" is the user defined replacement for "unknown".

**Comment by test-fullautomation** [comment]
Hi Holger,

BaseTests will have a directory, where a substring can match.

The idea of "unknown" is to identify new tests which are not assigned to any component up to now.
Usually a test suite grows continuously which makes the possibility high that new component tests are introduced at any time.

In this case your  proposal would mix BaseTests with new tests from any other component.

So, I will close this proposal to let our implementation as it is.

Thank you,
 Thomas
