### ISSUE TITLE
Mapping mechanism requires consideration of an additional tag attribute

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/python-pytestlog2db#17]
pytest allows to define an own suite name. This happens within the pytest ini file of the suite and changes in XML file the default value
`<testsuite name="pytest" ...`
to an own one, e.g.:
`<testsuite name="PythonExtensionsCollection" ...`

It would be helpful to have this information available within the mapping mechanism.

The requirement is:

In case of the test suite name is not the default "pytest", the content of this tag attribute shall be added as prefix to the class name.

In case of this is the class name:

`classname="Comparison.test_CComparison.Test_CComparison"`

the new class name shall be:

`PythonExtensionsCollection.Comparison.test_CComparison.Test_CComparison`

This would allow a more precise mapping like this:

`"PythonExtensionsCollection" ; "PythonExtensionsCollection"`

instead of:

`"PythonExtensionsCollection" ; "Comparison"`

**Comment by HolQue** [comment]
Ini file:

`junit_suite_name=PythonExtensionsCollection`

**Comment by test-fullautomation** [comment]
Hi Ngoan,
please look into this.
Thank you,
 Thomas

**Comment by ngoan1608** [comment]
> The requirement is:
> 
> In case of the test suite name is not the default "pytest", the content of this tag attribute shall be added as prefix to the class name.
> 
> In case of this is the class name:
> 
> `classname="Comparison.test_CComparison.Test_CComparison"`
> 
> the new class name shall be:
> 
> `PythonExtensionsCollection.Comparison.test_CComparison.Test_CComparison`
> 
> This would allow a more precise mapping like this:
> 
> `"PythonExtensionsCollection" ; "PythonExtensionsCollection"`
> 
> instead of:
> 
> `"PythonExtensionsCollection" ; "Comparison"`

Hi Holger,

Pytest already supports exactly your wish with the below argument:
`--junit-prefix=str      prepend prefix to classnames in junit-xml output`

Please add the `--junit-prefix=PythonExtensionsCollection` argument when executing pytest, the `classname` in the generated 
 report *xml file will be as your expectation. Then the mapping will be precise as your mentioned.

Please try and give your feedback in case this request is still required.

Thank you,
Ngoan

**Comment by HolQue** [comment]
Great! Works like described!

Ticket can be closed.
