### ISSUE TITLE
New UUID in append mode

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/python-pytestlog2db#18]
In command line of PyTestLog2DB I provide a **new!** UUID in append mode. This means in database is nothing to append to with this UUID.

Please clarify what is the desired outcome in such a case?

A possibility is to handle this as error. Another possibility is simply to add the new test results under the given UUID.

The current outcome is: The new test results are added to database but the component name is listed twice in component list
and in component diagrams of dashboard.

This I do not understand. What is the meaning? I would prefer to have an error message.

**Comment by HolQue** [comment]
RobotLog2DB has same issue

**Comment by test-fullautomation** [comment]
Hi Ngoan,

in case of a UUID *and* append mode is used and there is no dataset under the given UUID existing I would expect an error message. We can't append to a not existing dataset. This also avoids accidentally written datasets.

Thank you,
 Thomas

**Comment by HolQue** [comment]
Got proper error message.
(retest with latest available feature branches / 28.02.2023)

**Comment by test-fullautomation** [comment]
merged and solved with #20
