### ISSUE TITLE
XSD file not installed

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/python-pytestlog2db#22]
Hi Ngoan,

you need to extend the

`"PACKAGEDATA" : ["*.pdf"],`

by

`"PACKAGEDATA" : ["*.pdf","./xsd/*.xsd"],`

to get the xsd file installed also ;-)

**Comment by test-fullautomation** [comment]
Hi Ngoan,
please solve this with high prio.
Thank you,
 Thomas

**Comment by HolQue** [comment]
Installation and syntax error handling work properly now.

**Comment by ngoan1608** [comment]
Hi Thomas,

This issue was fixed in merged PR https://github.com/test-fullautomation/python-pytestlog2db/pull/24

Thank you,
Ngoan

**Comment by test-fullautomation** [comment]
solved and already merged with #24
