### ISSUE TITLE
XML syntax error causes crash

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/python-pytestlog2db#23]
lxml.etree.XMLSyntaxError: Opening and ending tag mismatch: testsuitesYZX line 1 and testsuites, line 1, column 19500

try/except needed to avoid crash because of corrpted XML files.

**Comment by test-fullautomation** [comment]
Hi Ngoan,

please look into this.

Thank you,
 Thomas

**Comment by HolQue** [comment]
Installation and syntax error handling work properly now.

**Comment by ngoan1608** [comment]
Hi Thomas,

This issue was fixed in merged PR https://github.com/test-fullautomation/python-pytestlog2db/pull/24

Thank you,
Ngoan

**Comment by test-fullautomation** [comment]
solved and already merged with #24
