### ISSUE TITLE
setup.py fails despite lxml is part of dependency list

### ISSUE THREAD

**Issue by test-fullautomation** [test-fullautomation/python-pytestlog2db#30]
setup.py fails despite lxml is part of dependency list
Reproduce: uninstall python lxml, start setup.py.

https://github.com/test-fullautomation/python-pytestlog2db/actions/runs/4820308674/jobs/8584620705

setup must first install dependencies, then import lxml.

**Comment by ngoan1608** [comment]
This issue has been fixed with merged PR https://github.com/test-fullautomation/python-pytestlog2db/pull/32 and can be closed.

**Comment by test-fullautomation** [comment]
solved and merged with #32
