### ISSUE TITLE
build for pypi fails due to missing dependencies

### ISSUE THREAD

**Issue by test-fullautomation** [test-fullautomation/python-pytestlog2db#31]
build for pypi fails due to missing dependencies

I tried to fix some, but it still fails:
https://github.com/test-fullautomation/python-pytestlog2db/actions/runs/4820502612/jobs/8585074171

**Comment by ngoan1608** [comment]
This issue has been fixed with merged PR #32 and can be closed.

**Comment by test-fullautomation** [comment]
solved and merged with #32
