### ISSUE TITLE
installation instruction outdated, webapp pictures not displayed

### ISSUE THREAD

**Issue by test-fullautomation** [test-fullautomation/python-pytestlog2db#35]
* "How to install
[PyTestLog2DB](https://github.com/test-fullautomation/python-pytestlog2db) is not available on [PyPI](https://pypi.org/) now."

Please use installtion instruction from genpackagedoc as template.

* WebApp pictures not displayed

**Comment by ngoan1608** [comment]
This issue has been fixed with merged PR #36 and it can be closed.

**Comment by test-fullautomation** [comment]
solved and merged with #36
