### ISSUE TITLE
import failed due to new pytest version 8.3.1

### ISSUE THREAD

**Issue by ngoan1608** [test-fullautomation/python-pytestlog2db#50]
Hi,

Below error occurs when importing *.xml result file which is generated by latest pytest version 8.3.1
`FATAL ERROR: Error when merging pytest xml files. Reason: unconverted data remains: +07:00`

Timezone is added for `timestamp` in generating xml file, this is not handled within `pytestlog2db` and cause the error.

Thank you,
Ngoan

**Comment by test-fullautomation** [comment]
Hi @ngoan1608 ,
what is the status of this issue?
Thank you,
 Thomas

**Comment by ngoan1608** [comment]
> Hi @ngoan1608 , what is the status of this issue? Thank you, Thomas

Hi Thomas,

I have updated label and status of this one.

Thank you for the reminder.
Ngoan

**Comment by test-fullautomation** [comment]
this is part of RobotFramework AIO 0.13.0
