### ISSUE TITLE
Some findings in documentation

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/python-pytestlog2db#6]
[PyTestLog2DB.pdf](https://github.com/test-fullautomation/python-pytestlog2db/files/10558402/PyTestLog2DB.pdf)

**Comment by test-fullautomation** [comment]
Hi Ngoan,
please look into this.
Thank you,
 Thomas

**Comment by HolQue** [comment]
Addentum to finding (3), based on latest things I learned in between ;-)

Regarding this example: 

`"Testsuite1" : "test-data.test_tsclass.TestSuite1",`

You should urgently add the following details, to give the audience a chance to understand the meaning:
* The entries in the mapping table refer to the content of the XML result file (and not immediately to the position of the executed pytest file within the file system).
* The XML result file does not contain the full path and name of the executed pytest file, but a so called "class name". Only this can be used to identify a component.
* This is the generic format of such a class name: `"<folder name>.<test file name>.<class name within test file code>"`

`<folder name>` can also be `<folder name>.<sub folder name>. ...` This depends on the working directory from which the pytest has been started!

This has some consequences:

Lots of test files containing lots of test classes may belong to one single component. It makes no sense to have the need to make in the mapping table a separate entry for every test file and every test class. Therefore only the folder name is left as criterion.

Also this works (and this should be recommended in the documentation):

`"Testsuite1" : "test-data",`

This requires that the names of all test folders within a project are unique over all components of this project.

**Comment by HolQue** [comment]
Further addendum:

At end of

https://github.com/test-fullautomation/python-pytestlog2db/issues/13

I proposed an alternative way to assign a test to a certain component. PyTestLog2DB will be able to handle this. Therefore it is not required to change the implementation.

But the possibility to do the assignment also in this alternative way needs to be explained in documentation.

**Comment by test-fullautomation** [comment]
Hi Ngoan,

can you please give me a status for this issue?

Thank you,
 Thomas

**Comment by ngoan1608** [comment]
Hi Thomas,

I have updated tool's document accordingly with PR #28 .

Thank you,
Ngoan

**Comment by test-fullautomation** [comment]
solved and merge with #28
