### ISSUE TITLE
Unfavorable error message in PyTestLog2DB

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/python-pytestlog2db#7]
pytestlog2db.py expects a result file in XML format. In such a result file I made the following error:

I added a closing bracket `>` after the opening `testsuite` tag.

Before: `<testsuites><testsuite name="pytest" errors="0" failures="0" skipped="0" ...`
After: `<testsuites><testsuite> name="pytest" errors="0" failures="0" skipped="0" ...`

This is not a syntax error, because the closing `testsuite` tag still exists. But the following tag attributes will not be recognized
any more by the XML parser, because now they are part of the tag content. Accessing a tag attribute that does not exist, causes an error. Therefore I would expect that it's possible to provide the name of the missing tag attribute in the error message.

But the error message is:

`FATAL ERROR: Error when merging pytest xml files. Reason: strptime() argument 1 must be str, not None`

(1)
Why "merging"? I would expect something like: "Error while parsing ..."

(2)
The "strptime() argument" hint is not really helpful. The error message should point more strict to the real root cause of the error: a missing tag attribute.

**Comment by HolQue** [comment]
The error message mentioned above, also occurs, if I pass an XML result file created by the Robot Framework.

But the XML result files of Robot Framework and pytest are  completely different ones. You urgently have to check the root tag of the XML files before you continue with parsing. If the root tag is not like expected, immediately the parsing should stop with a corresponding error message, telling about an invalid XML file type.

**Comment by test-fullautomation** [comment]
Hi Ngoan,
please look into this.
Thank you,
 Thomas

**Comment by HolQue** [comment]
Maybe this can be used for validating the XML files:

https://www.ibm.com/docs/de/developer-for-zos/14.1?topic=formats-junit-xml-format

**Comment by test-fullautomation** [comment]
merged and solved with #20
